//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int idMessage { get; set; }
        public string Subject { get; set; }
        public string Message1 { get; set; }
        public Nullable<int> IdSendBy { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Recruitment Recruitment { get; set; }
    }
}
