//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int idPosition { get; set; }
        public string PositionName { get; set; }
        public string PositionDescription { get; set; }
        public Nullable<int> idCompany { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Status { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
