//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public Recruitment()
        {
            this.Employees = new HashSet<Employee>();
            this.Messages = new HashSet<Message>();
        }
    
        public int idUser_ { get; set; }
        public string Name { get; set; }
        public string Paternal { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string isAdmin { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
    }
}
